### ISSUE TITLE
Compilation errors on Maven build

### ISSUE THREAD

**Issue by crapo** [owlcs/ont-api#31]
I cloned the repo and ran a Maven build. I get these two errors, which I also get if I import the code into Eclipse as a Maven project:
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/camfe/andy/ws/sadl/git/ont-api/ont-api/src/test/java/com/github/owlcs/ontapi/tests/managers/SimpleLoadTest.java:[120,45] incompatible types: inference variable T has incompatible bounds
    equality constraints: org.semanticweb.owlapi.model.OWLAxiom
    lower bounds: java.lang.Object
[ERROR] /home/camfe/andy/ws/sadl/git/ont-api/ont-api/src/test/java/com/github/owlcs/ontapi/utils/SP.java:[206,15] reference to Module is ambiguous
  both interface org.topbraid.spin.model.Module in org.topbraid.spin.model and class java.lang.Module in java.lang match

**Comment by sszuev** [comment]
I see you are using java9+ to compile (java11?).  
There is no such thing as `java.lang.Module` in java8 (ONT-API is java8-based API).

It seems right now there is no possibility to compile the whole project against java11.
But (I just checked) you can build it without tests: `mvn11 clean package -Dmaven.test.skip=true`.
Or use java8.

As for the compilation errors, 
the first class can be improved to be valid in java11 too (actually, it's strange why this class is not understood by a more fresh compiler, but that code is bit dirty);
the second class is a part of spin-tests, and it is better to remove it at all (#24 )
