### ISSUE TITLE
Getting error pulling maven deps

### ISSUE THREAD

**Issue by ont-app** [owlcs/ont-api#49]
This error is being generated when I execute the clojure command-line `clj -X:deps tree` after including this project as a dependency.

```
Error generating tree: Could not find artifact com.github.sszuev:concurrent-rdf-graph:jar:1.0.0 in central (https://repo1.maven.org/maven2/)
```
Version 3.0.4

**Comment by sszuev** [comment]
Hello

Currently, `concurrent-rdf-graph` is published in [jitpack](https://jitpack.io/#sszuev/concurrent-rdf-graph) , not maven-central.
For maven project need to add additional repo:
```xml
<repositories>
    <repository>
        <id>jitpack.io</id>
        <url>https://jitpack.io</url>
    </repository>
</repositories>
```
Perhaps there is a similar way in the clojure ecosystem?

(Maybe for the next release it is worth rewriting concurrent-rdf-graph in java and publishing it in maven-central.)

**Comment by ont-app** [comment]
Ah. Yes this is the configuration:
```
{
   :mvn/repos {"jitpack.io" {:url "https://jitpack.io"}}
   :deps
   {  ...
      com.github.owlcs/ontapi {:mvn/version "3.0.4"}
      ...
    }
  ...
}
```
Thanks! That fixed my problem!
